[package]
name = "sql-ddl-to-schema"
version = "0.1.1"
edition = "2021"

[dependencies]
linear-map = { version = "1.2.0", features = ["serde", "serde_impl"] }
serde = { version = "1.0.152", features = ["derive"] }
serde_yaml = "0.9.16"
sqlparser = "0.30.0"
